INSERT INTO TBL_CITY (NAME, PROVINCE) VALUES ('SOROCABA','SP');
INSERT INTO TBL_CITY (NAME, PROVINCE) VALUES ('CAMPINAS','SP');
INSERT INTO TBL_CITY (NAME, PROVINCE) VALUES ('PIRACICABA','SP');
INSERT INTO TBL_CITY (NAME, PROVINCE) VALUES ('SALTO','SP');
INSERT INTO TBL_CITY (NAME, PROVINCE) VALUES ('ITU','SP');