INSERT INTO TBL_CITY (NAME, PROVINCE, COUNTRY, POPULATION, AGE) VALUES ('SOROCABA','SP', 'BRASIL', '65MIL', '150ANOS');
INSERT INTO TBL_CITY (NAME, PROVINCE, COUNTRY, POPULATION, AGE) VALUES ('CAMPINAS','SP', 'BRASIL', '65MIL', '150ANOS');
INSERT INTO TBL_CITY (NAME, PROVINCE, COUNTRY, POPULATION, AGE) VALUES ('PIRACICABA','SP', 'BRASIL', '65MIL', '150ANOS');
INSERT INTO TBL_CITY (NAME, PROVINCE, COUNTRY, POPULATION, AGE) VALUES ('SALTO','SP', 'BRASIL', '65MIL', '150ANOS');
INSERT INTO TBL_CITY (NAME, PROVINCE, COUNTRY, POPULATION, AGE) VALUES ('ITU','SP', 'BRASIL', '65MIL', '150ANOS');